// Curated Unicode emoji set organised into the standard CLDR
// categories.  Inlined as a TS const so the picker has no
// runtime fetch and works offline.  Coverage targets the
// commonly-rendered Unicode 15 subgroups across every major
// platform (Apple Color, Noto, Segoe UI Emoji); rare regional
// indicators and the sequenced family/profession variants are
// intentionally omitted to keep the grid tractable.

export interface EmojiCategory {
  /** Stable key used by the picker for the active-tab state. */
  id: string
  /** Tab-strip label (one emoji — fits the 24x24 button cleanly). */
  icon: string
  /** Aria + hover label shown on the tab. */
  label: string
  emojis: string[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    icon: '😀',
    label: 'Smileys & Emotion',
    emojis: [
      '😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃','🫠','😉','😊','😇',
      '🥰','😍','🤩','😘','😗','☺️','😚','😙','🥲','😋','😛','😜','🤪','😝',
      '🤑','🤗','🤭','🫢','🫣','🤫','🤔','🫡','🤐','🤨','😐','😑','😶','🫥',
      '😶‍🌫️','😏','😒','🙄','😬','😮‍💨','🤥','🫨','😌','😔','😪','🤤','😴','😷',
      '🤒','🤕','🤢','🤮','🤧','🥵','🥶','🥴','😵','😵‍💫','🤯','🤠','🥳','🥸',
      '😎','🤓','🧐','😕','🫤','😟','🙁','☹️','😮','😯','😲','😳','🥺','🥹',
      '😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫',
      '🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩','🤡','👹','👺','👻',
      '👽','👾','🤖','😺','😸','😹','😻','😼','😽','🙀','😿','😾','🙈','🙉','🙊',
      '💋','💌','💘','💝','💖','💗','💓','💞','💕','💟','❣️','💔','❤️‍🔥','❤️‍🩹',
      '❤️','🧡','💛','💚','💙','🩵','💜','🤎','🖤','🩶','🤍','💯','💢','💥','💫','💦','💨','🕳️','💬','👁️‍🗨️','🗨️','🗯️','💭','💤',
    ],
  },
  {
    id: 'people',
    icon: '👋',
    label: 'People & Body',
    emojis: [
      '👋','🤚','🖐️','✋','🖖','🫱','🫲','🫳','🫴','🫷','🫸','👌','🤌','🤏',
      '✌️','🤞','🫰','🤟','🤘','🤙','👈','👉','👆','🖕','👇','☝️','🫵','👍',
      '👎','✊','👊','🤛','🤜','👏','🙌','🫶','👐','🤲','🤝','🙏','✍️','💅',
      '🤳','💪','🦾','🦵','🦿','🦶','👂','🦻','👃','🧠','🫀','🫁','🦷','🦴',
      '👀','👁️','👅','👄','🫦','👶','🧒','👦','👧','🧑','👱','👨','🧔','🧔‍♂️',
      '🧔‍♀️','👨‍🦰','👨‍🦱','👨‍🦳','👨‍🦲','👩','👩‍🦰','🧑‍🦰','👩‍🦱','🧑‍🦱','👩‍🦳','🧑‍🦳','👩‍🦲','🧑‍🦲',
      '👱‍♀️','👱‍♂️','🧓','👴','👵','🙍','🙎','🙅','🙆','💁','🙋','🧏','🙇','🤦',
      '🤷','🧑‍⚕️','👨‍⚕️','👩‍⚕️','🧑‍🎓','🧑‍🏫','🧑‍⚖️','🧑‍🌾','🧑‍🍳','🧑‍🔧','🧑‍🏭','🧑‍💼','🧑‍🔬','🧑‍💻',
      '🧑‍🎤','🧑‍🎨','🧑‍✈️','🧑‍🚀','🧑‍🚒','👮','🕵️','💂','🥷','👷','🫅','🤴','👸','👳',
      '👲','🧕','🤵','👰','🤰','🫃','🫄','🤱','🧑‍🍼','👼','🎅','🤶','🧑‍🎄','🦸',
      '🦹','🧙','🧚','🧛','🧜','🧝','🧞','🧟','🧌','💆','💇','🚶','🧍','🧎',
      '🧑‍🦯','🧑‍🦼','🧑‍🦽','🏃','💃','🕺','🕴️','👯','🧖','🧗','🤺','🏇','⛷️','🏂',
      '🏌️','🏄','🚣','🏊','⛹️','🏋️','🚴','🚵','🤸','🤼','🤽','🤾','🤹','🧘','🛀','🛌',
    ],
  },
  {
    id: 'animals',
    icon: '🐶',
    label: 'Animals & Nature',
    emojis: [
      '🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐻‍❄️','🐨','🐯','🦁','🐮','🐷',
      '🐽','🐸','🐵','🙈','🙉','🙊','🐒','🐔','🐧','🐦','🐦‍⬛','🐤','🐣','🐥',
      '🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🪱','🐛','🦋','🐌','🐞',
      '🐜','🪰','🪲','🪳','🦟','🦗','🕷️','🕸️','🦂','🐢','🐍','🦎','🦖','🦕',
      '🐙','🦑','🪼','🦐','🦞','🦀','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🦭',
      '🐊','🐅','🐆','🦓','🦍','🦧','🐘','🦣','🦛','🦏','🐪','🐫','🦒','🦘',
      '🦬','🐃','🐂','🐄','🐎','🐖','🐏','🐑','🦙','🐐','🦌','🐕','🐩','🦮',
      '🐕‍🦺','🐈','🐈‍⬛','🪶','🐓','🦃','🦤','🦚','🦜','🦢','🦩','🕊️','🐇','🦝',
      '🦨','🦡','🦫','🦦','🦥','🐁','🐀','🐿️','🦔','🐾','🐉','🐲','🌵','🎄',
      '🌲','🌳','🌴','🪹','🪺','🌱','🌿','☘️','🍀','🎍','🪴','🎋','🍃','🍂',
      '🍁','🍄','🐚','🪨','🌾','💐','🌷','🌹','🥀','🌺','🌸','🌼','🌻','🌞',
      '🌝','🌛','🌜','🌚','🌕','🌖','🌗','🌘','🌑','🌒','🌓','🌔','🌙','🌎','🌍','🌏','🪐','💫','⭐','🌟','✨','⚡','☄️','💥','🔥','🌪️','🌈','☀️','🌤️','⛅','🌥️','☁️','🌦️','🌧️','⛈️','🌩️','🌨️','❄️','☃️','⛄','🌬️','💨','💧','💦','🫧','☔','☂️','🌊','🌫️',
    ],
  },
  {
    id: 'food',
    icon: '🍔',
    label: 'Food & Drink',
    emojis: [
      '🍏','🍎','🍐','🍊','🍋','🍌','🍉','🍇','🍓','🫐','🍈','🍒','🍑','🥭',
      '🍍','🥥','🥝','🍅','🍆','🥑','🫛','🥦','🥬','🥒','🌶️','🫑','🌽','🥕',
      '🫒','🧄','🧅','🥔','🍠','🫚','🥐','🥯','🍞','🥖','🥨','🧀','🥚','🍳',
      '🧈','🥞','🧇','🥓','🥩','🍗','🍖','🦴','🌭','🍔','🍟','🍕','🫓','🥪',
      '🥙','🧆','🌮','🌯','🫔','🥗','🥘','🫕','🥫','🫙','🍝','🍜','🍲','🍛',
      '🍣','🍱','🥟','🦪','🍤','🍙','🍚','🍘','🍥','🥠','🥮','🍢','🍡','🍧',
      '🍨','🍦','🥧','🧁','🍰','🎂','🍮','🍭','🍬','🍫','🍿','🍩','🍪','🌰',
      '🥜','🫘','🍯','🥛','🫗','🍼','🫖','☕','🍵','🧃','🥤','🧋','🍶','🍺',
      '🍻','🥂','🍷','🥃','🍸','🍹','🧉','🍾','🧊','🥄','🍴','🍽️','🥣','🥡','🥢','🧂',
    ],
  },
  {
    id: 'travel',
    icon: '🚗',
    label: 'Travel & Places',
    emojis: [
      '🚗','🚕','🚙','🚌','🚎','🏎️','🚓','🚑','🚒','🚐','🛻','🚚','🚛','🚜',
      '🦯','🦽','🦼','🛴','🚲','🛵','🏍️','🛺','🛞','🚨','🚔','🚍','🚘','🚖',
      '🚡','🚠','🚟','🚃','🚋','🚞','🚝','🚄','🚅','🚈','🚂','🚆','🚇','🚊',
      '🚉','✈️','🛫','🛬','🛩️','💺','🛰️','🚀','🛸','🚁','🛶','⛵','🚤','🛥️',
      '🛳️','⛴️','🚢','⚓','🛟','🪝','⛽','🚧','🚦','🚥','🚏','🗺️','🗿','🗽',
      '🗼','🏰','🏯','🏟️','🎡','🎢','🛝','🎠','⛲','⛱️','🏖️','🏝️','🏜️','🌋',
      '⛰️','🏔️','🗻','🏕️','⛺','🛖','🏠','🏡','🏘️','🏚️','🏗️','🏭','🏢','🏬',
      '🏣','🏤','🏥','🏦','🏨','🏪','🏫','🏩','💒','🏛️','⛪','🕌','🕍','🛕',
      '🕋','⛩️','🛤️','🛣️','🗾','🎑','🏞️','🌅','🌄','🌠','🎇','🎆','🌇','🌆','🏙️','🌃','🌌','🌉','🌁',
    ],
  },
  {
    id: 'activities',
    icon: '⚽',
    label: 'Activities',
    emojis: [
      '⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🥏','🎱','🪀','🏓','🏸','🏒',
      '🏑','🥍','🏏','🪃','🥅','⛳','🪁','🏹','🎣','🤿','🥊','🥋','🎽','🛹',
      '🛼','🛷','⛸️','🥌','🎿','⛷️','🏂','🪂','🏋️','🤸','🤺','⛹️','🤾','🏌️',
      '🏇','🧘','🏄','🏊','🤽','🚣','🧗','🚵','🚴','🏆','🥇','🥈','🥉','🏅',
      '🎖️','🏵️','🎗️','🎫','🎟️','🎪','🤹','🎭','🩰','🎨','🎬','🎤','🎧','🎼',
      '🎹','🥁','🪘','🎷','🎺','🪗','🎸','🪕','🎻','🪈','🎲','♟️','🎯','🎳','🎮','🎰','🧩',
    ],
  },
  {
    id: 'objects',
    icon: '💡',
    label: 'Objects',
    emojis: [
      '⌚','📱','📲','💻','⌨️','🖥️','🖨️','🖱️','🖲️','🕹️','🗜️','💽','💾','💿',
      '📀','📼','📷','📸','📹','🎥','📽️','🎞️','📞','☎️','📟','📠','📺','📻',
      '🎙️','🎚️','🎛️','🧭','⏱️','⏲️','⏰','🕰️','⌛','⏳','📡','🔋','🪫','🔌',
      '💡','🔦','🕯️','🪔','🧯','🛢️','💸','💵','💴','💶','💷','🪙','💰','💳',
      '🧾','💎','⚖️','🪜','🧰','🪛','🔧','🔨','⚒️','🛠️','⛏️','🪚','🔩','⚙️',
      '🪤','🧱','⛓️','🧲','🔫','💣','🧨','🪓','🔪','🗡️','⚔️','🛡️','🚬','⚰️',
      '🪦','⚱️','🏺','🔮','📿','🧿','🪬','💈','⚗️','🔭','🔬','🕳️','🩻','🩹',
      '🩺','💊','💉','🩸','🧬','🦠','🧫','🧪','🌡️','🧹','🪠','🧺','🧻','🚽',
      '🚰','🚿','🛁','🛀','🧼','🪥','🪒','🧽','🪣','🧴','🛎️','🔑','🗝️','🚪',
      '🪑','🛋️','🛏️','🛌','🧸','🪆','🖼️','🪞','🪟','🛍️','🛒','🎁','🎈','🎏',
      '🎀','🪄','🪅','🎊','🎉','🎎','🏮','🎐','🪩','🧧','✉️','📩','📨','📧',
      '💌','📥','📤','📦','🏷️','🪧','📪','📫','📬','📭','📮','📯','📜','📃',
      '📄','📑','🧾','📊','📈','📉','🗒️','🗓️','📆','📅','🗑️','📇','🗃️','🗳️',
      '🗄️','📋','📁','📂','🗂️','🗞️','📰','📓','📔','📒','📕','📗','📘','📙',
      '📚','📖','🔖','🧷','🔗','📎','🖇️','📐','📏','🧮','📌','📍','✂️','🖊️',
      '🖋️','✒️','🖌️','🖍️','📝','✏️','🔍','🔎','🔏','🔐','🔒','🔓',
    ],
  },
  {
    id: 'symbols',
    icon: '❤️',
    label: 'Symbols',
    emojis: [
      '❤️','🧡','💛','💚','💙','🩵','💜','🖤','🩶','🤍','🤎','💔','❣️','💕','💞','💓','💗','💖','💘','💝','💟',
      '☮️','✝️','☪️','🕉️','☸️','🪯','✡️','🔯','🕎','☯️','☦️','🛐','⛎','♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓',
      '🆔','⚛️','🉑','☢️','☣️','📴','📳','🈶','🈚','🈸','🈺','🈷️','✴️','🆚','💮','🉐','㊙️','㊗️','🈴','🈵','🈹','🈲','🅰️','🅱️','🆎','🆑','🅾️','🆘','❌','⭕','🛑','⛔','📛','🚫','💯','💢','♨️','🚷','🚯','🚳','🚱','🔞','📵','🚭',
      '❗','❕','❓','❔','‼️','⁉️','🔅','🔆','〽️','⚠️','🚸','🔱','⚜️','🔰','♻️','✅','🈯','💹','❇️','✳️','❎','🌐','💠','Ⓜ️','🌀','💤','🏧','🚾','♿','🅿️','🛗','🈳','🈂️','🛂','🛃','🛄','🛅','🚹','🚺','🚼','⚧️','🚻','🚮','🎦','📶','🈁','🔣','ℹ️','🔤','🔡','🔠','🆖','🆗','🆙','🆒','🆕','🆓',
      '0️⃣','1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣','🔟','🔢','#️⃣','*️⃣','⏏️','▶️','⏸️','⏯️','⏹️','⏺️','⏭️','⏮️','⏩','⏪','⏫','⏬','◀️','🔼','🔽','➡️','⬅️','⬆️','⬇️','↗️','↘️','↙️','↖️','↕️','↔️','↪️','↩️','⤴️','⤵️','🔀','🔁','🔂','🔄','🔃',
      '🎵','🎶','➕','➖','➗','✖️','🟰','♾️','💲','💱','™️','©️','®️','〰️','➰','➿','🔚','🔙','🔛','🔝','🔜','✔️','☑️','🔘','🔴','🟠','🟡','🟢','🔵','🟣','⚫','⚪','🟤','🔺','🔻','🔸','🔹','🔶','🔷','🔳','🔲','▪️','▫️','◾','◽','◼️','◻️','🟥','🟧','🟨','🟩','🟦','🟪','⬛','⬜','🟫','🔈','🔇','🔉','🔊','🔔','🔕','📣','📢','👁️‍🗨️','💬','💭','🗯️','♠️','♣️','♥️','♦️','🃏','🎴','🀄',
    ],
  },
  {
    id: 'flags',
    icon: '🏳️',
    label: 'Flags',
    emojis: [
      '🏁','🚩','🎌','🏴','🏳️','🏳️‍🌈','🏳️‍⚧️','🏴‍☠️',
      '🇦🇨','🇦🇩','🇦🇪','🇦🇫','🇦🇬','🇦🇮','🇦🇱','🇦🇲','🇦🇴','🇦🇶','🇦🇷','🇦🇸','🇦🇹','🇦🇺','🇦🇼','🇦🇽','🇦🇿',
      '🇧🇦','🇧🇧','🇧🇩','🇧🇪','🇧🇫','🇧🇬','🇧🇭','🇧🇮','🇧🇯','🇧🇱','🇧🇲','🇧🇳','🇧🇴','🇧🇶','🇧🇷','🇧🇸','🇧🇹','🇧🇼','🇧🇾','🇧🇿',
      '🇨🇦','🇨🇨','🇨🇩','🇨🇫','🇨🇬','🇨🇭','🇨🇮','🇨🇰','🇨🇱','🇨🇲','🇨🇳','🇨🇴','🇨🇵','🇨🇷','🇨🇺','🇨🇻','🇨🇼','🇨🇽','🇨🇾','🇨🇿',
      '🇩🇪','🇩🇬','🇩🇯','🇩🇰','🇩🇲','🇩🇴','🇩🇿',
      '🇪🇦','🇪🇨','🇪🇪','🇪🇬','🇪🇭','🇪🇷','🇪🇸','🇪🇹','🇪🇺',
      '🇫🇮','🇫🇯','🇫🇰','🇫🇲','🇫🇴','🇫🇷',
      '🇬🇦','🇬🇧','🇬🇩','🇬🇪','🇬🇫','🇬🇬','🇬🇭','🇬🇮','🇬🇱','🇬🇲','🇬🇳','🇬🇵','🇬🇶','🇬🇷','🇬🇸','🇬🇹','🇬🇺','🇬🇼','🇬🇾',
      '🇭🇰','🇭🇲','🇭🇳','🇭🇷','🇭🇹','🇭🇺',
      '🇮🇨','🇮🇩','🇮🇪','🇮🇱','🇮🇲','🇮🇳','🇮🇴','🇮🇶','🇮🇷','🇮🇸','🇮🇹','🇯🇪','🇯🇲','🇯🇴','🇯🇵',
      '🇰🇪','🇰🇬','🇰🇭','🇰🇮','🇰🇲','🇰🇳','🇰🇵','🇰🇷','🇰🇼','🇰🇾','🇰🇿',
      '🇱🇦','🇱🇧','🇱🇨','🇱🇮','🇱🇰','🇱🇷','🇱🇸','🇱🇹','🇱🇺','🇱🇻','🇱🇾',
      '🇲🇦','🇲🇨','🇲🇩','🇲🇪','🇲🇫','🇲🇬','🇲🇭','🇲🇰','🇲🇱','🇲🇲','🇲🇳','🇲🇴','🇲🇵','🇲🇶','🇲🇷','🇲🇸','🇲🇹','🇲🇺','🇲🇻','🇲🇼','🇲🇽','🇲🇾','🇲🇿',
      '🇳🇦','🇳🇨','🇳🇪','🇳🇫','🇳🇬','🇳🇮','🇳🇱','🇳🇴','🇳🇵','🇳🇷','🇳🇺','🇳🇿',
      '🇴🇲','🇵🇦','🇵🇪','🇵🇫','🇵🇬','🇵🇭','🇵🇰','🇵🇱','🇵🇲','🇵🇳','🇵🇷','🇵🇸','🇵🇹','🇵🇼','🇵🇾',
      '🇶🇦','🇷🇪','🇷🇴','🇷🇸','🇷🇺','🇷🇼',
      '🇸🇦','🇸🇧','🇸🇨','🇸🇩','🇸🇪','🇸🇬','🇸🇭','🇸🇮','🇸🇯','🇸🇰','🇸🇱','🇸🇲','🇸🇳','🇸🇴','🇸🇷','🇸🇸','🇸🇹','🇸🇻','🇸🇽','🇸🇾','🇸🇿',
      '🇹🇦','🇹🇨','🇹🇩','🇹🇫','🇹🇬','🇹🇭','🇹🇯','🇹🇰','🇹🇱','🇹🇲','🇹🇳','🇹🇴','🇹🇷','🇹🇹','🇹🇻','🇹🇼','🇹🇿',
      '🇺🇦','🇺🇬','🇺🇲','🇺🇳','🇺🇸','🇺🇾','🇺🇿',
      '🇻🇦','🇻🇨','🇻🇪','🇻🇬','🇻🇮','🇻🇳','🇻🇺','🇼🇫','🇼🇸','🇽🇰','🇾🇪','🇾🇹','🇿🇦','🇿🇲','🇿🇼',
      '🏴󠁧󠁢󠁥󠁮󠁧󠁿','🏴󠁧󠁢󠁳󠁣󠁴󠁿','🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    ],
  },
]

/** Flat list across every category, useful for free-text search. */
export const ALL_EMOJIS: string[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis)

// ── Keyword index for the picker's search box (#144) ─────────
// Maps each emoji to a space-separated string of search terms.
// Hand-curated for the ~300 highest-traffic emojis; everything
// else falls back to its category label so a search like
// "flag" still surfaces the whole flags grid even where a
// specific country term isn't listed below.
//
// Keep entries lowercase; the picker lowercases the query
// before matching.
//
// To extend: just add an entry.  Multiple comma-/space-
// separated synonyms are fine ("dog puppy canine") — the
// picker does a substring match.
export const EMOJI_KEYWORDS: Record<string, string> = {
  // Smileys & Emotion
  '😀': 'grinning happy smile face',
  '😃': 'grinning happy smile face mouth',
  '😄': 'grinning happy smile face eyes',
  '😁': 'beam grin happy smile face',
  '😆': 'laugh happy grin smile face',
  '😅': 'sweat laugh grin smile face',
  '🤣': 'rofl rolling laugh happy lol',
  '😂': 'joy laugh tears happy lol crying',
  '🙂': 'slight smile happy face',
  '🙃': 'upside down silly face',
  '🫠': 'melting face hot embarrassed',
  '😉': 'wink happy face',
  '😊': 'blush happy smile face',
  '😇': 'angel halo innocent face',
  '🥰': 'love heart smile face',
  '😍': 'love heart eyes face',
  '🤩': 'star eyes wow excited face',
  '😘': 'kiss heart love face',
  '😗': 'kiss face',
  '☺️': 'smile blush face',
  '😚': 'kiss closed eyes face',
  '😙': 'kiss smile face',
  '🥲': 'happy crying smile tear face',
  '😋': 'yum tasty tongue face',
  '😛': 'tongue silly playful face',
  '😜': 'wink tongue silly face',
  '🤪': 'crazy zany silly face',
  '😝': 'tongue squint silly face',
  '🤑': 'money mouth dollar rich face',
  '🤗': 'hug hands open face',
  '🤭': 'oops shock giggle hand face',
  '🫢': 'shock gasp surprise hand face',
  '🫣': 'peek hide shy hand face',
  '🤫': 'shush quiet silence finger face',
  '🤔': 'think ponder hand face',
  '🫡': 'salute respect face',
  '🤐': 'zip mouth quiet silent face',
  '🤨': 'eyebrow skeptical doubt face',
  '😐': 'neutral meh blank face',
  '😑': 'expressionless blank face',
  '😶': 'silent no mouth face',
  '🫥': 'dotted invisible hidden face',
  '😏': 'smirk smug face',
  '😒': 'unamused annoyed face',
  '🙄': 'eye roll annoyed face',
  '😬': 'grimace awkward face',
  '🤥': 'lying liar pinocchio face',
  '😌': 'relieved calm relaxed face',
  '😔': 'pensive sad sorry face',
  '😪': 'sleepy tired face',
  '🤤': 'drool sleep face',
  '😴': 'sleep snore zzz face',
  '😷': 'mask sick medical face',
  '🤒': 'sick fever thermometer face',
  '🤕': 'hurt injured bandage face',
  '🤢': 'sick nauseated green face',
  '🤮': 'vomit puke sick face',
  '🤧': 'sneeze cold tissue face',
  '🥵': 'hot sweat heat face',
  '🥶': 'cold freezing ice face',
  '🥴': 'woozy drunk dizzy face',
  '😵': 'dizzy dead xx face',
  '🤯': 'mind blown shock face',
  '🤠': 'cowboy hat face',
  '🥳': 'party celebrate hat face',
  '🥸': 'disguise glasses moustache face',
  '😎': 'cool sunglasses face',
  '🤓': 'nerd glasses face',
  '🧐': 'monocle inspect face',
  '😕': 'confused unsure face',
  '🙁': 'frown sad face',
  '☹️': 'frown sad unhappy face',
  '😮': 'surprise shock open mouth face',
  '😯': 'hushed quiet face',
  '😲': 'astonished shocked face',
  '😳': 'flushed embarrassed blush face',
  '🥺': 'pleading puppy eyes face',
  '🥹': 'holding back tears face',
  '😨': 'fear scared face',
  '😰': 'anxious worry sweat face',
  '😢': 'cry sad tear face',
  '😭': 'sob crying tears sad face',
  '😱': 'scream scared horror face',
  '😞': 'sad disappointed face',
  '😩': 'weary tired sad face',
  '😫': 'tired exhausted face',
  '🥱': 'yawn tired bored face',
  '😤': 'huff angry steam face',
  '😡': 'angry red mad face',
  '😠': 'angry mad face',
  '🤬': 'cursing swear angry face',
  '😈': 'devil evil purple face',
  '👿': 'imp angry devil purple face',
  '💀': 'skull dead death',
  '☠️': 'skull crossbones death poison',
  '💩': 'poop poo shit',
  '🤡': 'clown circus',
  '👹': 'ogre demon japanese',
  '👺': 'goblin japanese',
  '👻': 'ghost halloween spooky',
  '👽': 'alien ufo space',
  '👾': 'space invader monster game',
  '🤖': 'robot ai bot',
  '😺': 'cat happy smile',
  '😸': 'cat grin smile happy',
  '😹': 'cat laugh tears joy',
  '😻': 'cat heart eyes love',
  '😼': 'cat smirk',
  '😽': 'cat kiss',
  '🙀': 'cat shock surprise',
  '😿': 'cat cry sad',
  '😾': 'cat angry mad',
  '🙈': 'monkey see no evil',
  '🙉': 'monkey hear no evil',
  '🙊': 'monkey speak no evil',
  '💋': 'kiss mark lips lipstick',
  '💌': 'love letter heart mail',
  '💘': 'heart arrow love cupid',
  '💝': 'heart gift ribbon love',
  '💖': 'sparkling heart love',
  '💗': 'growing heart love',
  '💓': 'beating heart love',
  '💞': 'revolving hearts love',
  '💕': 'two hearts love',
  '💟': 'heart decoration love',
  '❣️': 'heart exclamation love',
  '💔': 'broken heart sad',
  '❤️‍🔥': 'heart fire burning love',
  '❤️‍🩹': 'mending heart bandage',
  '❤️': 'red heart love',
  '🧡': 'orange heart love',
  '💛': 'yellow heart love',
  '💚': 'green heart love',
  '💙': 'blue heart love',
  '🩵': 'light blue heart love',
  '💜': 'purple heart love',
  '🤎': 'brown heart love',
  '🖤': 'black heart love',
  '🩶': 'grey gray heart love',
  '🤍': 'white heart love',
  '💯': 'hundred 100 perfect score',
  '💢': 'anger angry symbol',
  '💥': 'collision boom explosion',
  '💫': 'dizzy stars sparkle',
  '💦': 'sweat water drops',
  '💨': 'wind dash fart fast',
  '💬': 'speech bubble talk chat',
  '💭': 'thought bubble think',
  '💤': 'zzz sleep snore',

  // Hands / People — common ones
  '👋': 'wave hand hi hello bye',
  '🤚': 'hand raised back',
  '✋': 'hand stop high five',
  '🖖': 'vulcan spock star trek hand',
  '👌': 'ok okay perfect hand',
  '🤏': 'pinch small hand',
  '✌️': 'peace victory v hand',
  '🤞': 'fingers crossed luck hand',
  '🤟': 'love rock i love you hand',
  '🤘': 'rock metal horns hand',
  '🤙': 'call me phone hand shaka',
  '👈': 'point left hand',
  '👉': 'point right hand',
  '👆': 'point up hand',
  '👇': 'point down hand',
  '☝️': 'index up one hand',
  '👍': 'thumbs up like good yes hand',
  '👎': 'thumbs down dislike bad no hand',
  '✊': 'fist raised power hand',
  '👊': 'fist bump punch hand',
  '👏': 'clap applause hand',
  '🙌': 'raised hands praise celebrate',
  '🫶': 'heart hands love',
  '🤝': 'handshake deal agreement',
  '🙏': 'pray thanks please hand',
  '✍️': 'write writing pen hand',
  '💅': 'nail polish manicure',
  '💪': 'muscle flex strong arm',
  '👀': 'eyes look see watch',
  '👁️': 'eye look see',
  '👶': 'baby infant',
  '🧒': 'child kid',
  '🧑': 'person adult',
  '👨': 'man male',
  '👩': 'woman female',
  '🧓': 'older person elderly',
  '👴': 'old man grandpa',
  '👵': 'old woman grandma',
  '🤵': 'tuxedo groom suit',
  '👰': 'bride wedding veil',
  '👼': 'baby angel',
  '🎅': 'santa christmas',
  '🤶': 'mrs claus christmas',
  '🦸': 'superhero hero',
  '🦹': 'supervillain villain',
  '🧙': 'mage wizard magic',
  '🧚': 'fairy magic',
  '🧛': 'vampire dracula',
  '🧜': 'merperson mermaid',
  '🧝': 'elf',
  '🧞': 'genie',
  '🧟': 'zombie',
  '💃': 'dance dancing woman',
  '🕺': 'dance dancing man',
  '🚶': 'walk walking',
  '🏃': 'run running',
  '🧘': 'yoga meditation lotus',
  '🛌': 'sleep bed',
  '🛀': 'bath bathtub',

  // Animals & Nature
  '🐶': 'dog puppy face',
  '🐱': 'cat kitten face',
  '🐭': 'mouse face',
  '🐹': 'hamster face',
  '🐰': 'rabbit bunny face',
  '🦊': 'fox face',
  '🐻': 'bear face',
  '🐼': 'panda face',
  '🐻‍❄️': 'polar bear',
  '🐨': 'koala face',
  '🐯': 'tiger face',
  '🦁': 'lion face',
  '🐮': 'cow face',
  '🐷': 'pig face',
  '🐸': 'frog face',
  '🐵': 'monkey face',
  '🐔': 'chicken face',
  '🐧': 'penguin face',
  '🐦': 'bird face',
  '🦆': 'duck',
  '🦅': 'eagle',
  '🦉': 'owl',
  '🦇': 'bat',
  '🐺': 'wolf',
  '🐗': 'boar pig',
  '🐴': 'horse face',
  '🦄': 'unicorn',
  '🐝': 'bee honey',
  '🐛': 'bug caterpillar',
  '🦋': 'butterfly',
  '🐌': 'snail',
  '🐞': 'ladybug',
  '🐜': 'ant',
  '🕷️': 'spider',
  '🐍': 'snake',
  '🦖': 't-rex dinosaur',
  '🦕': 'sauropod dinosaur',
  '🐙': 'octopus',
  '🦐': 'shrimp prawn',
  '🦞': 'lobster',
  '🦀': 'crab',
  '🐠': 'fish tropical',
  '🐟': 'fish',
  '🐬': 'dolphin',
  '🐳': 'whale',
  '🦈': 'shark',
  '🐊': 'crocodile alligator',
  '🦓': 'zebra',
  '🐘': 'elephant',
  '🦒': 'giraffe',
  '🐪': 'camel',
  '🐎': 'horse',
  '🐑': 'sheep',
  '🐐': 'goat',
  '🐕': 'dog',
  '🐈': 'cat',
  '🦔': 'hedgehog',
  '🐉': 'dragon',
  '🌵': 'cactus',
  '🎄': 'christmas tree',
  '🌲': 'evergreen tree',
  '🌳': 'tree',
  '🌴': 'palm tree',
  '🌱': 'seedling sprout plant',
  '🌿': 'herb plant',
  '☘️': 'shamrock',
  '🍀': 'four leaf clover luck',
  '🍂': 'fallen leaves autumn',
  '🍁': 'maple leaf canada',
  '🍄': 'mushroom',
  '🐚': 'shell sea',
  '🌾': 'wheat',
  '💐': 'bouquet flowers',
  '🌷': 'tulip flower',
  '🌹': 'rose flower',
  '🌺': 'hibiscus flower',
  '🌸': 'cherry blossom flower sakura',
  '🌼': 'blossom flower',
  '🌻': 'sunflower',
  '🌞': 'sun face',
  '🌙': 'moon crescent',
  '⭐': 'star',
  '🌟': 'glowing star sparkle',
  '✨': 'sparkles glitter',
  '⚡': 'lightning bolt zap',
  '🔥': 'fire flame hot lit',
  '🌈': 'rainbow',
  '☀️': 'sun sunny',
  '⛅': 'cloud sun partly',
  '☁️': 'cloud',
  '🌧️': 'rain cloud',
  '⛈️': 'storm thunder rain',
  '🌨️': 'snow cloud',
  '❄️': 'snowflake snow cold',
  '☃️': 'snowman',
  '⛄': 'snowman without snow',
  '💧': 'droplet water',
  '☔': 'umbrella rain',
  '☂️': 'umbrella',
  '🌊': 'wave water ocean',

  // Food & Drink
  '🍎': 'apple red fruit',
  '🍏': 'green apple fruit',
  '🍊': 'orange tangerine fruit',
  '🍋': 'lemon fruit',
  '🍌': 'banana fruit',
  '🍉': 'watermelon fruit',
  '🍇': 'grapes fruit',
  '🍓': 'strawberry fruit',
  '🫐': 'blueberries fruit',
  '🍒': 'cherries fruit',
  '🍑': 'peach butt fruit',
  '🥭': 'mango fruit',
  '🍍': 'pineapple fruit',
  '🥝': 'kiwi fruit',
  '🍅': 'tomato',
  '🍆': 'eggplant aubergine',
  '🥑': 'avocado',
  '🥦': 'broccoli',
  '🥒': 'cucumber',
  '🌶️': 'hot pepper chili spicy',
  '🌽': 'corn',
  '🥕': 'carrot',
  '🥔': 'potato',
  '🍠': 'sweet potato',
  '🥐': 'croissant',
  '🥯': 'bagel',
  '🍞': 'bread loaf',
  '🥖': 'baguette bread',
  '🧀': 'cheese',
  '🥚': 'egg',
  '🍳': 'cooking egg pan',
  '🥞': 'pancakes',
  '🥓': 'bacon',
  '🥩': 'steak meat',
  '🍗': 'chicken poultry leg',
  '🍖': 'meat bone',
  '🌭': 'hot dog',
  '🍔': 'burger hamburger',
  '🍟': 'fries french',
  '🍕': 'pizza',
  '🥪': 'sandwich',
  '🌮': 'taco',
  '🌯': 'burrito',
  '🥗': 'salad green',
  '🍝': 'spaghetti pasta',
  '🍜': 'ramen noodles',
  '🍲': 'pot stew food',
  '🍱': 'bento japanese',
  '🍣': 'sushi',
  '🍤': 'shrimp tempura fried',
  '🍙': 'rice ball japanese',
  '🍚': 'rice',
  '🍦': 'ice cream soft',
  '🍨': 'ice cream',
  '🍩': 'donut doughnut',
  '🍪': 'cookie biscuit',
  '🎂': 'birthday cake',
  '🍰': 'cake slice',
  '🧁': 'cupcake',
  '🍫': 'chocolate bar',
  '🍬': 'candy sweet',
  '🍭': 'lollipop sweet',
  '🍯': 'honey pot',
  '🍿': 'popcorn',
  '🥛': 'milk glass',
  '☕': 'coffee tea hot',
  '🍵': 'tea green',
  '🧃': 'juice box',
  '🥤': 'cup drink soda',
  '🍶': 'sake japanese',
  '🍺': 'beer mug',
  '🍻': 'beers cheers',
  '🥂': 'champagne clink toast',
  '🍷': 'wine glass',
  '🍸': 'cocktail martini',
  '🍹': 'tropical drink',

  // Travel & Places
  '🚗': 'car automobile',
  '🚕': 'taxi cab',
  '🚙': 'suv jeep',
  '🚌': 'bus',
  '🚓': 'police car',
  '🚑': 'ambulance',
  '🚒': 'fire engine truck',
  '🚚': 'truck delivery',
  '🚜': 'tractor',
  '🏎️': 'race car',
  '🏍️': 'motorcycle',
  '🚲': 'bicycle bike',
  '🛴': 'scooter kick',
  '🛵': 'scooter motor',
  '🚂': 'locomotive steam train',
  '🚆': 'train',
  '🚇': 'metro subway',
  '🚊': 'tram',
  '✈️': 'airplane plane flight',
  '🛫': 'takeoff plane',
  '🛬': 'landing plane',
  '🚀': 'rocket launch space',
  '🛸': 'ufo flying saucer',
  '🚁': 'helicopter',
  '⛵': 'sailboat boat',
  '🚤': 'speedboat',
  '🚢': 'ship cruise',
  '⚓': 'anchor',
  '⛽': 'fuel gas pump',
  '🚦': 'traffic light',
  '🗺️': 'map world',
  '🗿': 'moai statue',
  '🗽': 'statue of liberty',
  '🗼': 'tokyo tower',
  '🏰': 'castle',
  '🏯': 'japanese castle',
  '🎡': 'ferris wheel',
  '🎢': 'roller coaster',
  '🎠': 'carousel horse',
  '⛲': 'fountain',
  '🏖️': 'beach',
  '🏝️': 'island desert',
  '🏜️': 'desert',
  '🌋': 'volcano',
  '⛰️': 'mountain',
  '🏔️': 'snow mountain',
  '🏕️': 'camping tent',
  '🏠': 'house home',
  '🏡': 'house garden home',
  '🏢': 'office building',
  '🏥': 'hospital',
  '🏦': 'bank',
  '🏨': 'hotel',
  '🏫': 'school',
  '⛪': 'church',
  '🕌': 'mosque',
  '🕍': 'synagogue',
  '🌅': 'sunrise',
  '🌄': 'sunrise mountain',
  '🌃': 'night stars',
  '🌆': 'sunset cityscape',
  '🌇': 'sunset',
  '🌉': 'bridge night',

  // Activities
  '⚽': 'soccer football',
  '🏀': 'basketball',
  '🏈': 'american football',
  '⚾': 'baseball',
  '🥎': 'softball',
  '🎾': 'tennis',
  '🏐': 'volleyball',
  '🏉': 'rugby',
  '🥏': 'frisbee disc',
  '🎱': 'pool 8 ball billiards',
  '🏓': 'ping pong table tennis',
  '🏸': 'badminton',
  '🏒': 'ice hockey',
  '🏑': 'field hockey',
  '🏏': 'cricket',
  '🥅': 'goal net',
  '⛳': 'golf flag',
  '🏹': 'bow arrow archery',
  '🎣': 'fishing pole',
  '🥊': 'boxing glove',
  '🥋': 'martial arts uniform',
  '🛹': 'skateboard',
  '⛸️': 'ice skate',
  '🥌': 'curling stone',
  '🎿': 'skis ski',
  '🏂': 'snowboard',
  '🏋️': 'weight lifting gym',
  '🚴': 'cycling bike',
  '🏆': 'trophy winner',
  '🥇': 'gold medal first',
  '🥈': 'silver medal second',
  '🥉': 'bronze medal third',
  '🏅': 'sports medal',
  '🎖️': 'military medal',
  '🎗️': 'reminder ribbon',
  '🎫': 'ticket',
  '🎟️': 'admission ticket',
  '🎪': 'circus tent',
  '🎭': 'performing arts theater masks',
  '🎨': 'artist palette art paint',
  '🎬': 'clapper film movie',
  '🎤': 'microphone mic karaoke',
  '🎧': 'headphones music',
  '🎼': 'musical score',
  '🎹': 'piano keyboard music',
  '🥁': 'drum music',
  '🎷': 'saxophone music',
  '🎺': 'trumpet music',
  '🎸': 'guitar music',
  '🎻': 'violin music',
  '🎲': 'dice game',
  '🎯': 'target dart bullseye',
  '🎳': 'bowling',
  '🎮': 'video game controller',
  '🎰': 'slot machine casino',
  '🧩': 'puzzle piece',

  // Objects
  '⌚': 'watch wrist time',
  '📱': 'phone mobile cellphone',
  '💻': 'laptop computer',
  '⌨️': 'keyboard',
  '🖥️': 'desktop computer',
  '🖨️': 'printer',
  '🖱️': 'computer mouse',
  '💾': 'floppy disk save',
  '💿': 'cd disc',
  '📷': 'camera photo',
  '📹': 'video camera',
  '🎥': 'movie camera',
  '📞': 'telephone phone',
  '📟': 'pager',
  '📺': 'tv television',
  '📻': 'radio',
  '🎙️': 'studio microphone',
  '🧭': 'compass',
  '⏰': 'alarm clock',
  '⌛': 'hourglass done',
  '⏳': 'hourglass flowing',
  '🔋': 'battery',
  '🔌': 'plug electric',
  '💡': 'light bulb idea',
  '🔦': 'flashlight torch',
  '🕯️': 'candle',
  '💸': 'money flying dollar',
  '💵': 'dollar bill cash',
  '💶': 'euro bill',
  '💷': 'pound bill',
  '🪙': 'coin',
  '💰': 'money bag',
  '💳': 'credit card',
  '💎': 'diamond gem',
  '⚖️': 'balance scale justice',
  '🔧': 'wrench tool',
  '🔨': 'hammer tool',
  '🛠️': 'tools hammer wrench',
  '⛏️': 'pick axe mining',
  '⚙️': 'gear settings cog',
  '🧱': 'brick',
  '🔫': 'water gun',
  '💣': 'bomb',
  '🔪': 'knife kitchen',
  '⚔️': 'crossed swords',
  '🛡️': 'shield',
  '🚬': 'cigarette smoking',
  '⚰️': 'coffin',
  '🏺': 'amphora pot',
  '🔮': 'crystal ball magic',
  '📿': 'prayer beads',
  '🧿': 'nazar evil eye',
  '🪬': 'hamsa',
  '🔭': 'telescope',
  '🔬': 'microscope',
  '💊': 'pill medicine',
  '💉': 'syringe injection',
  '🩸': 'blood drop',
  '🧬': 'dna',
  '🧪': 'test tube',
  '🌡️': 'thermometer temperature',
  '🚿': 'shower',
  '🛁': 'bathtub',
  '🧼': 'soap',
  '🛎️': 'bellhop bell',
  '🔑': 'key',
  '🚪': 'door',
  '🛋️': 'couch sofa',
  '🛏️': 'bed',
  '🧸': 'teddy bear',
  '🖼️': 'frame picture',
  '🛍️': 'shopping bags',
  '🛒': 'shopping cart',
  '🎁': 'gift present box',
  '🎈': 'balloon',
  '🎀': 'ribbon bow',
  '🎉': 'party popper celebration',
  '🎊': 'confetti ball party',
  '🧧': 'red envelope money',
  '✉️': 'envelope mail',
  '📧': 'email mail',
  '📨': 'incoming envelope mail',
  '📩': 'envelope arrow mail',
  '📦': 'package box',
  '🏷️': 'label tag',
  '📜': 'scroll paper',
  '📝': 'memo note pencil',
  '📰': 'newspaper',
  '📚': 'books',
  '📖': 'open book reading',
  '🔖': 'bookmark',
  '🔗': 'link chain',
  '📎': 'paperclip',
  '📌': 'pushpin pin',
  '📍': 'round pushpin location',
  '✂️': 'scissors cut',
  '🖊️': 'pen',
  '🖋️': 'fountain pen',
  '🖌️': 'paintbrush',
  '🖍️': 'crayon',
  '✏️': 'pencil',
  '🔍': 'search magnifying glass',
  '🔒': 'lock locked',
  '🔓': 'unlock unlocked',

  // Symbols
  '✅': 'check mark green correct done',
  '❌': 'cross x wrong no',
  '⭕': 'circle red',
  '🛑': 'stop sign',
  '⛔': 'no entry',
  '🚫': 'prohibited no',
  '❗': 'exclamation red',
  '❓': 'question red',
  '⚠️': 'warning caution',
  '♻️': 'recycle',
  '✔️': 'check tick',
  '➕': 'plus add',
  '➖': 'minus subtract',
  '✖️': 'multiply x',
  '➗': 'divide',
  '🟰': 'equals',
  '♾️': 'infinity',
  '💲': 'dollar',
  '™️': 'trademark',
  '©️': 'copyright',
  '®️': 'registered',
  '🔔': 'bell notification',
  '🔕': 'bell muted off',
  '📣': 'megaphone announcement',
  '📢': 'loudspeaker announcement',
  '0️⃣': 'zero 0 keycap number',
  '1️⃣': 'one 1 keycap number',
  '2️⃣': 'two 2 keycap number',
  '3️⃣': 'three 3 keycap number',
  '4️⃣': 'four 4 keycap number',
  '5️⃣': 'five 5 keycap number',
  '6️⃣': 'six 6 keycap number',
  '7️⃣': 'seven 7 keycap number',
  '8️⃣': 'eight 8 keycap number',
  '9️⃣': 'nine 9 keycap number',
  '🔟': 'ten 10 keycap number',
  '▶️': 'play',
  '⏸️': 'pause',
  '⏹️': 'stop',
  '⏭️': 'next track skip',
  '⏮️': 'previous track',
  '⏩': 'fast forward',
  '⏪': 'rewind',
  '🔀': 'shuffle',
  '🔁': 'repeat loop',
  '🔂': 'repeat once',
  '🎵': 'music note',
  '🎶': 'music notes',
  '🔴': 'red circle dot',
  '🟠': 'orange circle',
  '🟡': 'yellow circle',
  '🟢': 'green circle',
  '🔵': 'blue circle',
  '🟣': 'purple circle',
  '⚫': 'black circle',
  '⚪': 'white circle',
  '🟤': 'brown circle',
  '🟥': 'red square',
  '🟧': 'orange square',
  '🟨': 'yellow square',
  '🟩': 'green square',
  '🟦': 'blue square',
  '🟪': 'purple square',
  '⬛': 'black square',
  '⬜': 'white square',
  '🟫': 'brown square',
  '♠️': 'spade card',
  '♣️': 'club card',
  '♥️': 'heart card',
  '♦️': 'diamond card',

  // Flags — popular ones
  '🏳️': 'white flag',
  '🏴': 'black flag',
  '🏁': 'checkered flag finish race',
  '🚩': 'triangular flag red',
  '🏳️‍🌈': 'rainbow flag pride lgbt',
  '🏳️‍⚧️': 'transgender flag pride',
  '🏴‍☠️': 'pirate flag skull',
  '🇺🇸': 'usa united states america flag',
  '🇩🇪': 'germany deutschland flag',
  '🇫🇷': 'france french flag',
  '🇬🇧': 'united kingdom uk britain england flag',
  '🇪🇸': 'spain espana flag',
  '🇮🇹': 'italy italia flag',
  '🇵🇹': 'portugal flag',
  '🇳🇱': 'netherlands dutch holland flag',
  '🇧🇪': 'belgium flag',
  '🇨🇭': 'switzerland swiss flag',
  '🇦🇹': 'austria flag',
  '🇸🇪': 'sweden flag',
  '🇳🇴': 'norway flag',
  '🇩🇰': 'denmark flag',
  '🇫🇮': 'finland flag',
  '🇮🇪': 'ireland flag',
  '🇵🇱': 'poland flag',
  '🇨🇿': 'czech flag',
  '🇭🇺': 'hungary flag',
  '🇬🇷': 'greece flag',
  '🇹🇷': 'turkey flag',
  '🇷🇺': 'russia flag',
  '🇺🇦': 'ukraine flag',
  '🇨🇦': 'canada flag',
  '🇲🇽': 'mexico flag',
  '🇧🇷': 'brazil flag',
  '🇦🇷': 'argentina flag',
  '🇨🇱': 'chile flag',
  '🇯🇵': 'japan flag',
  '🇨🇳': 'china flag',
  '🇰🇷': 'south korea flag',
  '🇮🇳': 'india flag',
  '🇦🇺': 'australia flag',
  '🇳🇿': 'new zealand flag',
  '🇿🇦': 'south africa flag',
  '🇪🇬': 'egypt flag',
  '🇸🇦': 'saudi arabia flag',
  '🇮🇱': 'israel flag',
  '🇪🇺': 'european union eu flag',
}

/** Search index built once at module load — flattens emoji →
 *  search blob (keywords + category label) so the picker can
 *  do a cheap substring match per keystroke. */
export interface EmojiSearchEntry {
  emoji: string
  /** Lowercased searchable text: keywords plus category label. */
  search: string
}
export const EMOJI_SEARCH_INDEX: EmojiSearchEntry[] = (() => {
  const out: EmojiSearchEntry[] = []
  const seen = new Set<string>()
  for (const cat of EMOJI_CATEGORIES) {
    const catBlob = `${cat.label} ${cat.id}`.toLowerCase()
    for (const e of cat.emojis) {
      if (seen.has(e)) continue
      seen.add(e)
      const kw = (EMOJI_KEYWORDS[e] ?? '').toLowerCase()
      out.push({ emoji: e, search: `${kw} ${catBlob}` })
    }
  }
  return out
})()
