//! Nimbus — a modern mail client with Nextcloud integration.
//!
//! This is the Tauri application entry point. It registers Tauri
//! commands (the IPC bridge between Rust and Svelte) and launches
//! the native window.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use nimbus_core::NimbusError;
use nimbus_core::models::Account;
use nimbus_store::account_store;

// ── Tauri commands ──────────────────────────────────────────────
//
// Each `#[tauri::command]` function becomes callable from the
// Svelte frontend via `invoke("command_name", { args })`.
//
// Tauri serialises the return value as JSON and sends it to the
// frontend. Errors must implement `Serialize` (which NimbusError
// does) so Tauri can send them back as structured error objects.

/// Return all configured accounts.
#[tauri::command]
fn get_accounts() -> Result<Vec<Account>, NimbusError> {
    account_store::load_accounts()
}

/// Add a new email account.
///
/// The frontend sends an `Account` object; we persist it to disk.
/// The `id` should be generated by the frontend (e.g. a UUID).
#[tauri::command]
fn add_account(account: Account) -> Result<(), NimbusError> {
    account_store::add_account(account)
}

/// Remove an account by its ID.
#[tauri::command]
fn remove_account(id: String) -> Result<(), NimbusError> {
    account_store::remove_account(&id)
}

/// Update an existing account's settings.
#[tauri::command]
fn update_account(account: Account) -> Result<(), NimbusError> {
    account_store::update_account(account)
}

/// Stub: "test" a connection to the given server.
///
/// Right now this always succeeds — real IMAP/SMTP connection
/// testing will come when we implement Issue #1 (IMAP) and
/// Issue #2 (SMTP). For now it lets the UI flow work end-to-end.
#[tauri::command]
fn test_connection(host: String, port: u16) -> Result<String, NimbusError> {
    tracing::info!("Test connection to {host}:{port} (stub — always succeeds)");
    Ok(format!("Connection to {host}:{port} OK (stub)"))
}

// ── App entry point ─────────────────────────────────────────────

fn main() {
    tracing_subscriber::fmt::init();

    tauri::Builder::default()
        // Register all our commands so the frontend can call them
        .invoke_handler(tauri::generate_handler![
            get_accounts,
            add_account,
            remove_account,
            update_account,
            test_connection,
        ])
        .run(tauri::generate_context!())
        .expect("error while running Nimbus");
}
